server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: sports-management-system

  datasource:
    url: jdbc:postgresql://ep-crimson-star-aq1h28eq.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: ${DB_PASSWORD:npg_uCRK3kWFLHD1}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      uri: mongodb+srv://Grupo1:${MONGO_PASSWORD:passGrupo1}@trends.5fjep6r.mongodb.net/?appName=trends
      database: sports_metrics
      auto-index-creation: true

logging:
  level:
    root: INFO
    com.sports: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.jdbc: DEBUG
    org.mongodb: DEBUG